<a href="https://colab.research.google.com/github/Shlok1810/predict_the_electrical_energy_output_of_a_Combined_Cycle_Power_Plant/blob/main/Combined_cycle_power_plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [8]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [9]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [10]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [11]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [12]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 938us/step - loss: 115874.8517
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 244.7759
Epoch 3/100
240/240 [==============================] - 0s 917us/step - loss: 233.0260
Epoch 4/100
240/240 [==============================] - 0s 955us/step - loss: 213.3647
Epoch 5/100
240/240 [==============================] - 0s 990us/step - loss: 212.2358
Epoch 6/100
240/240 [==============================] - 0s 977us/step - loss: 194.9282
Epoch 7/100
240/240 [==============================] - 0s 944us/step - loss: 178.2472
Epoch 8/100
240/240 [==============================] - 0s 950us/step - loss: 160.5664
Epoch 9/100
240/240 [==============================] - 0s 953us/step - loss: 142.2721
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 121.4501
Epoch 11/100
240/240 [==============================] - 0s 1000us/step - loss: 102.2561
Epoch 12/100
240/240 [==============================

### Predicting the results of the Test set

In [20]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[431.31 431.23]
 [462.38 460.01]
 [465.92 461.14]
 ...
 [473.1  473.26]
 [439.93 438.  ]
 [459.11 463.28]]
